### ISSUE TITLE
Make this repo public?

### ISSUE THREAD

**Issue by ryan-n-may** [Keven-R/TicTac#113]
Hey! Hope your summer holidays are going well, 

Since the semester is over, can we make this repo public? Would be nice to see it on our pages

Let me know, 
Thanks
Ryan

**Comment by Keven-R** [comment]
no problem, made it public. Hope your holidays are going well too

**Comment by JasmineEllaine** [comment]
Heyo sorry just saw this but yes please, been meaning to put it on my folio
:)

Jasmine

---

*JASMINE BANARES*

*M: *0426 997 926

*E*: ***@***.***

*W*: jasmineellaine.tumblr.com

**Comment by Keven-R** [comment]
It should be public, let me know if it isn't for some reason
